### ISSUE TITLE
中文字符串排序

### ISSUE THREAD

**Issue by clumsyme** [clumsyme/blogs#4]
```js
// 字符串原型比较方法
a.localeCompare(b, 'zh-Hans-CN')

// 字符串数组排序
sa.sort((a, b) => a.localeCompare(b, 'zh-Hans-CN'))
// 或者比较属性
sa.sort((a, b) => a.name.localeCompare(b.name, 'zh-Hans-CN'))

// 大量数据使用Intl.Collator对象
var ic = new Intl.Collator('zh-Hans-CN')
sa.sort(ic.compare)
// 或者比较属性
sa.sort((a, b) => ic.compare(a.name, b.name))
```
---

[String.prototype.localeCompare()](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

**Comment by wenguangcheng** [comment]
这个比较是不准确的,如果遇到了多音字的问题就基本挂了一坨坨的

**Comment by clumsyme** [comment]
@wenguangcheng 你是指`localeCompare`方法吗，这个方法应该不同浏览器有不同实现，对多音字不同浏览器可能就有不同结果。
如果有自己的排序规则，应该只能自己实现整个方法了

**Comment by wenguangcheng** [comment]
@clumsyme 后来测试了一下，可以使用var ic = new Intl.Collator('zh-Hans-CN')，或者网站的一个拼音库，就可以解决一些多音字的问题，但是支持的很少
